baseURL = "https://www.pracujucemamy.sk"
defaultContentLanguage = "sk"
languageCode = "sk-sk"
title = "Pracujuce Mamy"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "section", "page"]

[params]
  beta = false
