name: github pages (beta)

on:
  push:
    branches:
      - beta  # Set a branch to deploy
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: HUGO_PARAMS_BETA=true hugo --minify -b https://beta.pracujucemamy.sk

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.BETA_PRACUJUCEMAMY_ACCESS_TOKEN }}
          external_repository: pracujucemamy/web-beta
          publish_branch: gh-pages # default: gh-pages
          publish_dir: ./public
          cname: beta.pracujucemamy.sk